package de.vimotest.examples.taskview;

/*Generated by MPS */


public class TaskListViewModelTestSetupImpl extends TaskListViewModelTestSetup {
  @Override
  public void Init() {
  }
  @Override
  public void SetDataTableJson(String json) {
  }
  @Override
  public TaskListViewModel BuildSut() {
    return null;
  }
}
