package de.vimotest.examples.taskview;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import java.util.List;
import org.junit.Assert;

public class TaskListViewModel_LoadTests_Test {
  private TaskListViewModel sut;
  private TaskListViewModelTestSetup testSetup;
  private String oneTask = "[ { id:\"0\", name:\"A\", priority:\"low\", dueDate:\"2024/12/01\" } ]";
  private String twoTasks = "[ { id:\"0\", name:\"A\" },\n  { id:\"1\", name:\"B\" } ]";
  private String priorityCombinations = "[ { id:\"0\", priority:\"low\" },\n  { id:\"1\", priority:\"medium\" },\n  { id:\"2\", priority:\"high\" } ]";
  private String dueDate2023 = "[ { id:\"0\", name:\"Task A\", dueDate:\"2023/01/01\" } ]";
  private String dueDate2024 = "[ { id:\"0\", name:\"Task A\", dueDate:\"2024/10/11\" } ]";
  @Test
  public void test_Load_Empty_Tasks_given_when_LoadView_then_Tasks_has_0_rows() throws Exception {
    this.BuildSut();
    this.when_LoadView();
    this.then_Tasks_has_0_rows();
  }
  @Test
  public void test_Load_one_Task_with_all_values_given_oneTask_when_LoadView_then_Tasks_has_1_rows() throws Exception {
    this.given_oneTask();
    this.BuildSut();
    this.when_LoadView();
    this.then_Tasks_has_1_rows();
  }
  @Test
  public void test_Initial_selection_given_twoTasks_when_LoadView_then_Tasks_has_2_rows_and_selected_row_handle_0() throws Exception {
    this.given_twoTasks();
    this.BuildSut();
    this.when_LoadView();
    this.then_Tasks_has_2_rows_and_selected_row_handle_0();
  }
  @Test
  public void test_Load_Tasks_with_all_three_priority_levels_given_priorityCombinations_when_LoadView_then_Tasks_has_3_rows() throws Exception {
    this.given_priorityCombinations();
    this.BuildSut();
    this.when_LoadView();
    this.then_Tasks_has_3_rows();
  }
  @Test
  public void test_Due_Date_from_2023_given_dueDate2023_when_LoadView_then_Tasks_has_1_rows() throws Exception {
    this.given_dueDate2023();
    this.BuildSut();
    this.when_LoadView();
    this.then_Tasks_has_1_rows_1();
  }
  @Test
  public void test_Due_Date_Tooltip_given_dueDate2024_when_LoadView_then_Tasks_has_1_rows() throws Exception {
    this.given_dueDate2024();
    this.BuildSut();
    this.when_LoadView();
    this.then_Tasks_has_1_rows_2();
  }
  @BeforeEach
  public void setUp() {
    this.testSetup = new TaskListViewModelTestSetupImpl();
    this.testSetup.Init();
  }



  protected void BuildSut() {
    this.sut = this.testSetup.BuildSut();
  }



  public void given_oneTask() {
    this.testSetup.SetDataTableJson(this.oneTask);
  }
  public void given_twoTasks() {
    this.testSetup.SetDataTableJson(this.twoTasks);
  }
  public void given_priorityCombinations() {
    this.testSetup.SetDataTableJson(this.priorityCombinations);
  }
  public void given_dueDate2023() {
    this.testSetup.SetDataTableJson(this.dueDate2023);
  }
  public void given_dueDate2024() {
    this.testSetup.SetDataTableJson(this.dueDate2024);
  }


  public void when_LoadView() {
    this.sut.loadView();
  }


  public void then_Tasks_has_0_rows() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals(Integer.valueOf(0), Integer.valueOf(actualRows.size()));
  }
  public void then_Tasks_has_1_rows() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("0", row0.getRowHandle());
    Assert.assertEquals("PrioLow", row0.getPriorityImageName());
    Assert.assertEquals("A", row0.getTaskNameLabelText());
    Assert.assertEquals("2024/12/01", row0.getDueDateLabelText());
    // }
  }
  public void then_Tasks_has_2_rows_and_selected_row_handle_0() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals(Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("0", row0.getRowHandle());
    Assert.assertEquals("A", row0.getTaskNameLabelText());
    // }
    // {
    TaskListViewModelTasksRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("1", row1.getRowHandle());
    Assert.assertEquals("B", row1.getTaskNameLabelText());
    // }
    Assert.assertEquals("0", this.sut.getTasksTableSelectedRow());
  }
  public void then_Tasks_has_3_rows() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals(Integer.valueOf(3), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("0", row0.getRowHandle());
    Assert.assertEquals("PrioLow", row0.getPriorityImageName());
    // }
    // {
    TaskListViewModelTasksRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("1", row1.getRowHandle());
    Assert.assertEquals("PrioMedium", row1.getPriorityImageName());
    // }
    // {
    TaskListViewModelTasksRow row2 = actualRows.get(3 - 1);
    Assert.assertEquals("2", row2.getRowHandle());
    Assert.assertEquals("PrioHigh", row2.getPriorityImageName());
    // }
  }
  public void then_Tasks_has_1_rows_1() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("0", row0.getRowHandle());
    Assert.assertEquals("Task A", row0.getTaskNameLabelText());
    Assert.assertEquals("red", row0.getTaskNameLabelTextColor());
    Assert.assertEquals("2023/01/01", row0.getDueDateLabelText());
    Assert.assertEquals("red", row0.getDueDateLabelTextColor());
    // }
  }
  public void then_Tasks_has_1_rows_2() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals(Integer.valueOf(1), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("0", row0.getRowHandle());
    Assert.assertEquals("2024/10/11", row0.getDueDateLabelText());
    Assert.assertEquals("11th October 2024", row0.getDueDateLabelToolTip());
    // }
  }
}
