package de.vimotest.examples.taskview;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import java.util.List;
import org.junit.Assert;

public class TaskListViewModel_AddDeleteTests_Test {
  private TaskListViewModel sut;
  private TaskListViewModelTestEnvironment testEnvironment;
  private String oneTask = "[ { id:\"0\", name:\"A\", priority:\"low\", dueDate:\"2024/12/01\" } ]";
  private String threeTasks = "[ { id:\"0\", name:\"A\" },\n  { id:\"1\", name:\"B\" },\n  { id:\"2\", name:\"C\" } ]";
  private String emptyTasks = "[ { id:\"0\", name:\"Task A\", dueDate:\"2023/01/01\" } ]";
  @Test
  public void test_Add_New_Task_given_oneTask_when_LoadViewModel_and_click_AddNewTask_then_Tasks_has_2_rows_and_selected_row_handle_1() throws Exception {
    this.given_oneTask();
    this.BuildSut();
    this.when_LoadViewModel();
    this.when_click_AddNewTask();
    this.then_Tasks_has_2_rows_and_selected_row_handle_1();
  }
  @Test
  public void test_Delete_Task_given_threeTasks_when_LoadViewModel_and_select_row_0_in_Tasks_and_click_DeleteTask_then_Tasks_has_2_rows_and_selected_row_handle_1() throws Exception {
    this.given_threeTasks();
    this.BuildSut();
    this.when_LoadViewModel();
    this.when_select_row_0_in_Tasks();
    this.when_click_DeleteTask();
    this.then_Tasks_has_2_rows_and_selected_row_handle_1_1();
  }
  @Test
  public void test_Delete_Task_given_threeTasks_when_LoadViewModel_and_select_row_1_in_Tasks_and_click_DeleteTask_then_Tasks_has_2_rows_and_selected_row_handle_2() throws Exception {
    this.given_threeTasks();
    this.BuildSut();
    this.when_LoadViewModel();
    this.when_select_row_1_in_Tasks();
    this.when_click_DeleteTask();
    this.then_Tasks_has_2_rows_and_selected_row_handle_2();
  }
  @Test
  public void test_Delete_Task_given_threeTasks_when_LoadViewModel_and_select_row_2_in_Tasks_and_click_DeleteTask_then_Tasks_has_2_rows_and_selected_row_handle_1() throws Exception {
    this.given_threeTasks();
    this.BuildSut();
    this.when_LoadViewModel();
    this.when_select_row_2_in_Tasks();
    this.when_click_DeleteTask();
    this.then_Tasks_has_2_rows_and_selected_row_handle_1_2();
  }
  @Test
  public void test_Delete_Task_given_threeTasks_when_LoadViewModel_and_click_DeleteTask_and_click_DeleteTask_and_click_DeleteTask_then_Tasks_has_0_rows() throws Exception {
    this.given_threeTasks();
    this.BuildSut();
    this.when_LoadViewModel();
    this.when_click_DeleteTask();
    this.when_click_DeleteTask();
    this.when_click_DeleteTask();
    this.then_Tasks_has_0_rows();
  }
  @Test
  public void test_Delete_disabled_if_nothing_selected_given_emptyTasks_when_LoadViewModel_and_select_row_0_in_Tasks_and_click_DeleteTask_then_AddNewTask_is_enabled_and_DeleteTask_is_not_enabled() throws Exception {
    this.given_emptyTasks();
    this.BuildSut();
    this.when_LoadViewModel();
    this.when_select_row_0_in_Tasks();
    this.when_click_DeleteTask();
    this.then_AddNewTask_is_enabled();
    this.then_DeleteTask_is_not_enabled();
  }
  @BeforeEach
  public void setUp() {
    this.testEnvironment = new TaskListViewModelTestEnvironmentImpl();
    this.testEnvironment.Init();
  }



  protected void BuildSut() {
    this.sut = this.testEnvironment.BuildSut();
  }



  public void given_oneTask() {
    this.testEnvironment.SetDataTableJson(this.oneTask);
  }
  public void given_threeTasks() {
    this.testEnvironment.SetDataTableJson(this.threeTasks);
  }
  public void given_emptyTasks() {
    this.testEnvironment.SetDataTableJson(this.emptyTasks);
  }


  public void when_LoadViewModel() {
    this.sut.loadViewModel();
  }
  public void when_click_AddNewTask() {
    this.sut.addNewTaskButtonClicked();
  }
  public void when_select_row_0_in_Tasks() {
    this.sut.tasksTableRowSelected("0");
  }
  public void when_click_DeleteTask() {
    this.sut.deleteTaskButtonClicked();
  }
  public void when_select_row_1_in_Tasks() {
    this.sut.tasksTableRowSelected("1");
  }
  public void when_select_row_2_in_Tasks() {
    this.sut.tasksTableRowSelected("2");
  }


  public void then_Tasks_has_2_rows_and_selected_row_handle_1() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals("Expected that table view Tasks has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 0 has rowhandle <0>, but was <" + row0.getRowHandle() + ">", "0", row0.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "A" + ">, but was <" + row0.getTaskNameLabelText() + ">", "A", row0.getTaskNameLabelText());
    // }
    // {
    TaskListViewModelTasksRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 1 has rowhandle <1>, but was <" + row1.getRowHandle() + ">", "1", row1.getRowHandle());
    Assert.assertEquals("Expected that image Priority has " + "image <PrioMedium>" + ", but was <" + row1.getPriorityImageName() + ">", "PrioMedium", row1.getPriorityImageName());
    Assert.assertEquals("Expected that label Task Name has text <" + "<New Task>" + ">, but was <" + row1.getTaskNameLabelText() + ">", "<New Task>", row1.getTaskNameLabelText());
    Assert.assertEquals("Expected that label Due Date has text <" + "" + ">, but was <" + row1.getDueDateLabelText() + ">", "", row1.getDueDateLabelText());
    // }
    Assert.assertEquals("Expected that table view Tasks has selected row with row handle <" + "1" + ">, but was <" + this.sut.getTasksTableSelectedRow() + ">", "1", this.sut.getTasksTableSelectedRow());
  }
  public void then_Tasks_has_2_rows_and_selected_row_handle_1_1() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals("Expected that table view Tasks has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 0 has rowhandle <1>, but was <" + row0.getRowHandle() + ">", "1", row0.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "B" + ">, but was <" + row0.getTaskNameLabelText() + ">", "B", row0.getTaskNameLabelText());
    // }
    // {
    TaskListViewModelTasksRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 1 has rowhandle <2>, but was <" + row1.getRowHandle() + ">", "2", row1.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "C" + ">, but was <" + row1.getTaskNameLabelText() + ">", "C", row1.getTaskNameLabelText());
    // }
    Assert.assertEquals("Expected that table view Tasks has selected row with row handle <" + "1" + ">, but was <" + this.sut.getTasksTableSelectedRow() + ">", "1", this.sut.getTasksTableSelectedRow());
  }
  public void then_Tasks_has_2_rows_and_selected_row_handle_2() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals("Expected that table view Tasks has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 0 has rowhandle <0>, but was <" + row0.getRowHandle() + ">", "0", row0.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "A" + ">, but was <" + row0.getTaskNameLabelText() + ">", "A", row0.getTaskNameLabelText());
    // }
    // {
    TaskListViewModelTasksRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 1 has rowhandle <2>, but was <" + row1.getRowHandle() + ">", "2", row1.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "C" + ">, but was <" + row1.getTaskNameLabelText() + ">", "C", row1.getTaskNameLabelText());
    // }
    Assert.assertEquals("Expected that table view Tasks has selected row with row handle <" + "2" + ">, but was <" + this.sut.getTasksTableSelectedRow() + ">", "2", this.sut.getTasksTableSelectedRow());
  }
  public void then_Tasks_has_2_rows_and_selected_row_handle_1_2() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals("Expected that table view Tasks has 2 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(2), Integer.valueOf(actualRows.size()));
    // {
    TaskListViewModelTasksRow row0 = actualRows.get(1 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 0 has rowhandle <0>, but was <" + row0.getRowHandle() + ">", "0", row0.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "A" + ">, but was <" + row0.getTaskNameLabelText() + ">", "A", row0.getTaskNameLabelText());
    // }
    // {
    TaskListViewModelTasksRow row1 = actualRows.get(2 - 1);
    Assert.assertEquals("Expected that table view Tasks row at index 1 has rowhandle <1>, but was <" + row1.getRowHandle() + ">", "1", row1.getRowHandle());
    Assert.assertEquals("Expected that label Task Name has text <" + "B" + ">, but was <" + row1.getTaskNameLabelText() + ">", "B", row1.getTaskNameLabelText());
    // }
    Assert.assertEquals("Expected that table view Tasks has selected row with row handle <" + "1" + ">, but was <" + this.sut.getTasksTableSelectedRow() + ">", "1", this.sut.getTasksTableSelectedRow());
  }
  public void then_Tasks_has_0_rows() {
    List<TaskListViewModelTasksRow> actualRows = this.sut.getTasksTableRows();
    Assert.assertEquals("Expected that table view Tasks has 0 rows, but has " + Integer.toString(actualRows.size()), Integer.valueOf(0), Integer.valueOf(actualRows.size()));
  }
  public void then_AddNewTask_is_enabled() {
    Assert.assertTrue("Expected button AddNewTask is enabled, but it was disabled", this.sut.getIsAddNewTaskButtonEnabled());
  }
  public void then_DeleteTask_is_not_enabled() {
    Assert.assertFalse("Expected button DeleteTask is disabled, but it was enabled", this.sut.getIsDeleteTaskButtonEnabled());
  }
}
