package de.vimotest.examples.taskview;

/*Generated by MPS */


public abstract class TaskListViewModelTasksRow {
  public abstract String getPriorityImageName();
  public abstract String getTaskNameLabelText();
  public abstract String getTaskNameLabelTextColor();
  public abstract String getDueDateLabelText();
  public abstract String getDueDateLabelToolTip();
  public abstract String getDueDateLabelTextColor();
  public abstract String getRowHandle();
}
