name: Build

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  buildAndTestTaskManager:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: actions/checkout@v4

      # Prepare MPS
      - name: Download and Prepare MPS
        run: sh ./gradlew prepareMps

      # Clean Project (source_gen of VCS)
      - name: Clean Project
        run: sh ./gradlew mpsClean

      # Build Project
      - name: Build Project
        run: sh ./gradlew mpsBuild

      # Build taskview example
      - name: Compile TaskView Example
        run: sh ./gradlew assemble
        working-directory: taskmanager

      # Test taskview example
      - name: Test TaskView Example
        run: sh ./gradlew test
        working-directory: taskmanager
